/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule CreateLinkPageQuery.graphql
 * @generated SignedSource<<1b934c442261999032eacaf5b3829c98>>
 * @relayHash ed0fac1ab14db3b6951b30e93fb85d6e
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/* eslint-disable comma-dangle, quotes */

/*
query CreateLinkPageQuery {
  viewer {
    ...CreateLink_viewer
    id
  }
}

fragment CreateLink_viewer on Viewer {
  id
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "CreateLinkPageQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": "viewer",
        "args": null,
        "concreteType": "Viewer",
        "name": "__viewer_viewer",
        "plural": false,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "CreateLink_viewer",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "CreateLinkPageQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "CreateLinkPageQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Viewer",
        "name": "viewer",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          }
        ],
        "storageKey": null
      },
      {
        "kind": "LinkedHandle",
        "alias": null,
        "args": null,
        "handle": "viewer",
        "name": "viewer",
        "key": "",
        "filters": null
      }
    ]
  },
  "text": "query CreateLinkPageQuery {\n  viewer {\n    ...CreateLink_viewer\n    id\n  }\n}\n\nfragment CreateLink_viewer on Viewer {\n  id\n}\n"
};

module.exports = batch;
