/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule CreateLink_viewer.flow
 * @generated SignedSource<<dec85680cf5c307d0fa040a0597e7b2e>>
 * @flow
 */

'use strict';

export type CreateLink_viewer = {
  id: string;
};
