/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Link_link.flow
 * @generated SignedSource<<12fbec7259c4ee1ac980b2420b9b18ea>>
 * @flow
 */

'use strict';

export type Link_link = {
  id: string;
  description: string;
  url: string;
  createdAt: any;
  postedBy?: ?Link_link_postedBy;
  votes?: ?Link_link_votes;
};

export type Link_link_postedBy = {
  id: string;
  name: string;
};

export type Link_link_votes_edges_node_user = {
  id: string;
};

export type Link_link_votes_edges_node = {
  id: string;
  user: Link_link_votes_edges_node_user;
};

export type Link_link_votes_edges = {
  node?: ?Link_link_votes_edges_node;
};

export type Link_link_votes = {
  edges?: ?Array<?Link_link_votes_edges>;
};
