/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Link_link.flow
 * @generated SignedSource<<c25f271a1539d07776690e6b3ec88e8b>>
 * @flow
 */

'use strict';

export type Link_link = {
  id: string;
  description: string;
  url: string;
  createdAt: any;
  postedBy?: ?Link_link_postedBy;
  votes?: ?Link_link_votes;
};

export type Link_link_postedBy = {
  id: string;
  name: string;
};

export type Link_link_votes = {
  count: number;
};
