/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule LinkList_viewer.graphql
 * @generated SignedSource<<52c74daea123bd0d11ca374cc03ac88b>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type LinkList_viewer = {
  allLinks?: ?LinkList_viewer_allLinks;
};

export type LinkList_viewer_allLinks_edges = {
  node?: ?any;
};

export type LinkList_viewer_allLinks_pageInfo = {
  hasNextPage?: ?boolean;
  endCursor?: ?string;
};

export type LinkList_viewer_allLinks = {
  edges?: ?Array<?LinkList_viewer_allLinks_edges>;
  pageInfo?: ?LinkList_viewer_allLinks_pageInfo;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [
    {
      "kind": "RootArgument",
      "name": "count",
      "type": "Int"
    },
    {
      "kind": "RootArgument",
      "name": "after",
      "type": "String"
    }
  ],
  "kind": "Fragment",
  "metadata": {
    "connection": [
      {
        "count": "count",
        "cursor": "after",
        "direction": "forward",
        "path": [
          "allLinks"
        ]
      }
    ]
  },
  "name": "LinkList_viewer",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": "allLinks",
      "args": [
        {
          "kind": "Literal",
          "name": "orderBy",
          "value": "createdAt_DESC",
          "type": "LinkOrderBy"
        }
      ],
      "concreteType": "LinkConnection",
      "name": "__LinkList_allLinks_connection",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "LinkEdge",
          "name": "edges",
          "plural": true,
          "selections": [
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "Link",
              "name": "node",
              "plural": false,
              "selections": [
                {
                  "kind": "FragmentSpread",
                  "name": "Link_link",
                  "args": null
                }
              ],
              "storageKey": null
            }
          ],
          "storageKey": null
        },
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "PageInfo",
          "name": "pageInfo",
          "plural": false,
          "selections": [
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "hasNextPage",
              "storageKey": null
            },
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "endCursor",
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": "__LinkList_allLinks_connection{\"orderBy\":\"createdAt_DESC\"}"
    }
  ],
  "type": "Viewer"
};

module.exports = fragment;
