/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule LinkList_viewer.flow
 * @generated SignedSource<<8ee0c55d55c6ca723596e3db15ac0775>>
 * @flow
 */

'use strict';

export type LinkList_viewer = {
  allLinks?: ?LinkList_viewer_allLinks;
};

export type LinkList_viewer_allLinks_edges = {
  node?: ?any;
};

export type LinkList_viewer_allLinks_pageInfo = {
  hasNextPage?: ?boolean;
  endCursor?: ?string;
};

export type LinkList_viewer_allLinks = {
  edges?: ?Array<?LinkList_viewer_allLinks_edges>;
  pageInfo?: ?LinkList_viewer_allLinks_pageInfo;
};
