/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Link_viewer.flow
 * @generated SignedSource<<dfde3b3639aa3ec5abd2cda95a7c752b>>
 * @flow
 */

'use strict';

export type Link_viewer = {
  id: string;
};
