/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule LinkList_viewer.graphql
 * @generated SignedSource<<14fe1b228030f9d8a5fb4dccfc689e39>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type LinkList_viewer = {
  id: string;
  allLinks?: ?LinkList_viewer_allLinks;
};

export type LinkList_viewer_allLinks_edges = {
  node?: ?any;
};

export type LinkList_viewer_allLinks = {
  edges?: ?Array<?LinkList_viewer_allLinks_edges>;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": {
    "connection": [
      {
        "count": null,
        "cursor": null,
        "direction": "backward",
        "path": [
          "allLinks"
        ]
      }
    ]
  },
  "name": "LinkList_viewer",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "FragmentSpread",
      "name": "Link_viewer",
      "args": null
    },
    {
      "kind": "LinkedField",
      "alias": "allLinks",
      "args": null,
      "concreteType": "LinkConnection",
      "name": "__LinkList_allLinks_connection",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "LinkEdge",
          "name": "edges",
          "plural": true,
          "selections": [
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "Link",
              "name": "node",
              "plural": false,
              "selections": [
                {
                  "kind": "FragmentSpread",
                  "name": "Link_link",
                  "args": null
                }
              ],
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "Viewer"
};

module.exports = fragment;
