/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule LinkList_viewer.flow
 * @generated SignedSource<<a264f7eb4e658f099e4866ed1225a03c>>
 * @flow
 */

'use strict';

export type LinkList_viewer = {
  id: string;
  allLinks?: ?LinkList_viewer_allLinks;
};

export type LinkList_viewer_allLinks_edges = {
  node?: ?any;
};

export type LinkList_viewer_allLinks_pageInfo = {
  hasNextPage?: ?boolean;
};

export type LinkList_viewer_allLinks = {
  edges?: ?Array<?LinkList_viewer_allLinks_edges>;
  pageInfo?: ?LinkList_viewer_allLinks_pageInfo;
};
