/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule LinkList_viewer.flow
 * @generated SignedSource<<bfe3b6ac3a6a1e46f2c53262fe0b9a41>>
 * @flow
 */

'use strict';

export type LinkList_viewer = {
  id: string;
  allLinks?: ?LinkList_viewer_allLinks;
};

export type LinkList_viewer_allLinks_edges = {
  node?: ?any;
};

export type LinkList_viewer_allLinks = {
  edges?: ?Array<?LinkList_viewer_allLinks_edges>;
};
